FROM redis
COPY redis.conf /usr/local/etc/redis/redis.conf
EXPOSE 7004                                                                         
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
